---
version: 1
disable_existing_loggers: false
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "%(levelprefix)s %(asctime)s - %(message)s"
    use_colors: true
    datefmt: "%Y-%m-%d %H:%M:%S"
  access:
    "()": uvicorn.logging.AccessFormatter
    fmt: '%(levelprefix)s %(asctime)s - %(client_addr)s - "%(request_line)s" %(status_code)s'
    use_colors: true
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn:
    handlers:
      - default
    level: DEBUG
    propagate: false
  uvicorn.error:
    level: DEBUG
  uvicorn.access:
    handlers:
      - access
    level: DEBUG
    propagate: false
  api:
    handlers:
      - default
    level: INFO
    propagate: false