name: Docker image
run-name: Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build-and-push:
    uses: suitenumerique/ci/.github/workflows/_docker-publish.yml@ca6401ac83e981e5b0a94f06f68baaa6e6d0a436 # v0.0.1
    with:
      image_name: lasuite/whisper-api
      context: .
      file: ./app/Dockerfile
      target: production
      docker_user: "1000"
      is_multi_platform: false
      should_push: ${{ github.event_name != 'pull_request' }}
      trivy_scan: false
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
